name: Android Build

on: pull_request_review

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble

